---
# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - curl

- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /data/nextcloud/mysql_admin_pass
    - /data/nextcloud/mysql_user_pass
  register: nextcloud_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ nextcloud_secrets.results | selectattr('item', 'equalto', '/data/nextcloud/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 
    mysql_user_pass: "{{ nextcloud_secrets.results | selectattr('item', 'equalto', '/data/nextcloud/mysql_user_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for nextcloud
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "/data/nextcloud/"
    - "/data/nextcloud/data/"
    - "/data/nextcloud/db/"

- name: create folder struct for nextcloud 2
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: 8983
    group: 8983
  with_items:
    - "/data/nextcloud/solr/"

- name: start nextcloud-solr docker
  docker_container: 
    name: nextcloud-solr
    image: solr:6.6
    hostname: nextcloud-solr
    state: started
    restart_policy: always
    volumes:
      - /data/nextcloud/solr/:/opt/solr/server/solr/mycores
    entrypoint:
      - "docker-entrypoint.sh solr-precreate nextcloud"

- name: start nextcloud-db docker
  docker_container: 
    name: nextcloud-db
    image: mariadb:10
    hostname: nextcloud-db
    state: started
    restart_policy: always
    volumes:
      - /data/nextcloud/db/:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
     
- name: start nextcloud-app docker
  docker_container: 
    name: nextcloud-app
    image: nextcloud:12.0-apache
    state: started
    restart_policy: always
    ports:
      - 127.0.0.1:42005:80
    links:
      - nextcloud-solr:solr
      - nextcloud-db:mysql
    volumes:
      - /data/nextcloud/data/:/var/www/html/

- name: Cronjob f√ºr nextcloud cron
  cron: name="nextcloud-cron" weekday="*" hour="*" minute="*/15" job=" curl --silent http://127.0.0.1:42005/cron.php"
